In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
ranking = pd.read_csv('/content/drive/MyDrive/Statistella/ranking.csv')
ranking[:5]

,TEAM_ID,LEAGUE_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,TEAM,G,W,L,W_PCT,HOME_RECORD,ROAD_RECORD,RETURNTOPLAY
0,1610612743,0,22022,2022-12-22,West,Denver,30,19,11,0.633,10-3,9-8,NaN
1,1610612763,0,22022,2022-12-22,West,Memphis,30,19,11,0.633,13-2,6-9,NaN
2,1610612740,0,22022,2022-12-22,West,New Orleans,31,19,12,0.613,13-4,6-8,NaN
3,1610612756,0,22022,2022-12-22,West,Phoenix,32,19,13,0.594,14-4,5-9,NaN
4,1610612746,0,22022,2022-12-22,West,LA Clippers,33,19,14,0.576,11-7,8-7,NaN

In [ ]:
ranking[['HOME_WINS', 'HOME_LOSSES']] = ranking['HOME_RECORD'].str.split('-', expand=True)

In [ ]:
ranking[['ROAD_WINS', 'ROAD_LOSSES']] = ranking['ROAD_RECORD'].str.split('-', expand=True)

In [ ]:
ranking['STANDINGSDATE'] = pd.to_datetime(ranking['STANDINGSDATE'])

In [ ]:
ranking.drop(columns=['HOME_RECORD', 'ROAD_RECORD'], inplace=True)

In [ ]:
ranking.drop(['LEAGUE_ID'], axis = 1, inplace = True)

In [ ]:
ranking['HOME_WINS'] = ranking['HOME_WINS'].astype(int)
ranking['HOME_LOSSES'] = ranking['HOME_LOSSES'].astype(int)
ranking['ROAD_WINS'] = ranking['ROAD_WINS'].astype(int)
ranking['ROAD_LOSSES'] = ranking['ROAD_LOSSES'].astype(int)

In [ ]:
ranking['SEASON_ID'].unique()

array([22022, 12022, 22021, 12021, 22020, 12020, 22019, 12019, 22013,
       12013, 22012, 12012, 22011, 12011, 22010, 12010, 22009, 12009,
       22008, 12008, 22007, 12007, 22006, 12006, 22005, 12005, 22004,
       12004, 22003, 12003, 22002, 22018, 12018, 22017, 12017, 22016,
       12016, 22015, 12015, 22014, 12014])

In [ ]:
ranking['SEASON_TYPE'] = ranking['SEASON_ID']//10000

In [ ]:
ranking['YEAR'] = ranking['SEASON_ID']%10000

In [ ]:
ranking[:5]

,TEAM_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,TEAM,G,W,L,W_PCT,RETURNTOPLAY,HOME_WINS,HOME_LOSSES,ROAD_WINS,ROAD_LOSSES,SEASON_TYPE,YEAR
0,1610612743,22022,2022-12-22,West,Denver,30,19,11,0.633,NaN,10,3,9,8,2,2022
1,1610612763,22022,2022-12-22,West,Memphis,30,19,11,0.633,NaN,13,2,6,9,2,2022
2,1610612740,22022,2022-12-22,West,New Orleans,31,19,12,0.613,NaN,13,4,6,8,2,2022
3,1610612756,22022,2022-12-22,West,Phoenix,32,19,13,0.594,NaN,14,4,5,9,2,2022
4,1610612746,22022,2022-12-22,West,LA Clippers,33,19,14,0.576,NaN,11,7,8,7,2,2022

In [ ]:
ranking['SEASON_TYPE'].unique()

array([2, 1])

In [ ]:
ranking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210342 entries, 0 to 210341
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TEAM_ID        210342 non-null  int64
 1   SEASON_ID      210342 non-null  int64
 2   STANDINGSDATE  210342 non-null  datetime64[ns]
 3   CONFERENCE     210342 non-null  object
 4   TEAM           210342 non-null  object
 5   G              210342 non-null  int64
 6   W              210342 non-null  int64
 7   L              210342 non-null  int64
 8   W_PCT          210342 non-null  float64
 9   RETURNTOPLAY   3990 non-null    float64
 10  HOME_WINS      210342 non-null  int64
 11  HOME_LOSSES    210342 non-null  int64
 12  ROAD_WINS      210342 non-null  int64
 13  ROAD_LOSSES    210342 non-null  int64
 14  SEASON_TYPE    210342 non-null  int64
 15  YEAR           210342 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(11), object(2)
memory usage: 25.7+ MB

In [ ]:
ranking['SEASON_TYPE'].value_counts()

SEASON_TYPE
2    197489
1     12853
Name: count, dtype: int64

In [ ]:
ranking.drop('TEAM', axis = 1, inplace = True)

In [ ]:
ranking[:5]

,TEAM_ID,SEASON_ID,STANDINGSDATE,CONFERENCE,G,W,L,W_PCT,RETURNTOPLAY,HOME_WINS,HOME_LOSSES,ROAD_WINS,ROAD_LOSSES,SEASON_TYPE,YEAR
0,1610612743,22022,2022-12-22,West,30,19,11,0.633,NaN,10,3,9,8,2,2022
1,1610612763,22022,2022-12-22,West,30,19,11,0.633,NaN,13,2,6,9,2,2022
2,1610612740,22022,2022-12-22,West,31,19,12,0.613,NaN,13,4,6,8,2,2022
3,1610612756,22022,2022-12-22,West,32,19,13,0.594,NaN,14,4,5,9,2,2022
4,1610612746,22022,2022-12-22,West,33,19,14,0.576,NaN,11,7,8,7,2,2022

In [ ]:
ranking.describe().T

,count,mean,min,25%,50%,75%,max,std
TEAM_ID,210342.0,1610612751.474071,1610612737.0,1610612744.0,1610612751.0,1610612759.0,1610612766.0,8.641501
SEASON_ID,210342.0,21401.054773,12003.0,22006.0,22011.0,22017.0,22022.0,2395.250417
STANDINGSDATE,210342,2013-05-18 08:09:33.009669888,2003-10-01 00:00:00,2008-07-31 00:00:00,2013-05-19 00:00:00,2018-03-07 00:00:00,2022-12-22 00:00:00,NaN
G,210342.0,56.659735,0.0,32.0,67.0,82.0,82.0,28.644294
W,210342.0,28.333357,0.0,14.0,28.0,42.0,73.0,17.2685
L,210342.0,28.326378,0.0,14.0,29.0,41.0,72.0,17.260557
W_PCT,210342.0,0.492833,0.0,0.372,0.5,0.621,1.0,0.187763
RETURNTOPLAY,3990.0,0.6,0.0,0.0,1.0,1.0,1.0,0.489959
HOME_WINS,210342.0,16.649105,0.0,8.0,17.0,25.0,40.0,10.051046
HOME_LOSSES,210342.0,11.682622,0.0,5.0,11.0,17.0,34.0,7.964306
ROAD_WINS,210342.0,11.684252,0.0,5.0,11.0,18.0,34.0,7.706264
ROAD_LOSSES,210342.0,16.643756,0.0,9.0,17.0,24.0,38.0,9.848962
SEASON_TYPE,210342.0,1.938895,1.0,2.0,2.0,2.0,2.0,0.239524
YEAR,210342.0,2012.107249,2002.0,2007.0,2012.0,2017.0,2022.0,5.540331

In [ ]:
ranking['TEAM_ID']

NameError: name 'ranking' is not defined

In [ ]:
ranking.to_csv('processed_ranking.csv', index=False)